### ISSUE TITLE
[UPG FAIL] Cannot download 'http://mirrorlist.centos.org/?release=8&arch=x86_64&repo=BaseOS': Cannot prepare internal mirrorlist: No URLs in mirrorlist.

### ISSUE THREAD

**Issue by imorandinwnp** [cpanel/elevate#384]
Hi,

Update fails on stage 3 with error described on the title.
This is an OpenVZ container and I'm using almaconvert8 utility.

```
Loaded plugins: langpacks, universal-hooks
No packages marked for update
An elevation process is currently in progress: running stage 3
You can check the log by running:
    /scripts/elevate-cpanel --log
or check the elevation status:
    /scripts/elevate-cpanel --check
Found /waiting_for_distro_upgrade file
1258: Elevate finished, conversion started.
Starting conversion: 1258 at 12:20:36.989289
base0                                                                                                                                | 2.9 kB  00:00:00
base6                                                                                                                                | 3.6 kB  00:00:00
Not using downloaded repomd.xml because it is older than what we have:
  Current   : Wed Feb 28 13:39:36 2024
  Downloaded: Thu Oct 29 17:03:00 2020
base7                                                                                                                                | 2.9 kB  00:00:00
base8                                                                                                                                | 2.9 kB  00:00:00
(1/2): base8/primary_db                                                                                                              | 250 kB  00:00:00
(2/2): base7/primary_db                                                                                                              |  25 MB  00:00:00
Package 1:ct-preset-common-12-01.01.noarch already installed and latest version
Package 1:ct-preset-systemd-12-01.01.noarch already installed and latest version
Package 1:vz-dummy-systemd-12-01.01.noarch already installed and latest version
Nothing to do
lock file /vz/template/centos/8/x86_64/.lock locked
template centos-8-x86_64 locked
update metadata for centos-8-x86_64
Temporary yum config /vz/tmp//vzpkg.cTJFUj/yum_conf.1yhmMk was created
Run /usr/share/vzyum/bin/yum from chroot(/vz/pkgenv/rpm414x64) with parameters:
/usr/share/vzyum/bin/yum
-y
-c
/vz/tmp//vzpkg.cTJFUj/yum_conf.1yhmMk
--basearch
x86_64
--installroot
/vz/tmp/vzpkg.cTJFUj
clean
metadata
--allowerasing
And environments:
LD_PRELOAD=/usr/libexec/vztt_checker_open.so
VZTT_VEROOT=/vz/tmp/vzpkg.cTJFUj
PYTHONPATH=/vz/pkgenv/rpm414x64/usr/lib64//python3.6
SYSTEMD_LOG_TARGET=console
DNF_RELEASEVER=8
DNF_PLATFORM_ID=platform:el8
VZCTL_ENV=RPM_INSTALL_PREFIX:SYSTEMD_LOG_TARGET:DNF_RELEASEVER:DNF_PLATFORM_ID
timer: config: 4 ms
DNF version: 4.0.9
Command: dnf -y -c /vz/tmp//vzpkg.cTJFUj/yum_conf.1yhmMk --basearch x86_64 --installroot /vz/tmp/vzpkg.cTJFUj clean metadata --allowerasing
Installroot: /vz/tmp/vzpkg.cTJFUj
Releasever: 8
cachedir: /vz/template/centos/8/x86_64/pm/
Base command: clean
Extra commands: ['-y', '-c', '/vz/tmp//vzpkg.cTJFUj/yum_conf.1yhmMk', '--basearch', 'x86_64', '--installroot', '/vz/tmp/vzpkg.cTJFUj', 'clean', 'metadata', '--allowerasing']
Cleaning data: metadata dbcache expire-cache
Cache was expired
Removing file /vz/template/centos/8/x86_64/pm/base0.solv
Removing file /vz/template/centos/8/x86_64/pm/base1.solv
Removing file /vz/template/centos/8/x86_64/pm/base1-filenames.solvx
Removing file /vz/template/centos/8/x86_64/pm/base0-filenames.solvx
Removing file /vz/template/centos/8/x86_64/pm/base0-a0b1f78487defd70/repodata/0fa70f6ba54b98bdce045eb112c22f6ba4fe6a19a24e64855bbfe83139953d63-primary.xml.gz
Removing file /vz/template/centos/8/x86_64/pm/base0-a0b1f78487defd70/repodata/b0d2ffc68fbf14f7c1cecf699d3822de44388c538839d11e5569a81b9f60cc59-filelists.xml.gz
Removing file /vz/template/centos/8/x86_64/pm/base0-a0b1f78487defd70/repodata/repomd.xml
Removing file /vz/template/centos/8/x86_64/pm/base1-898e42d315451c2d/mirrorlist
Removing file /vz/template/centos/8/x86_64/pm/base1-898e42d315451c2d/repodata/filelists.xml.gz
Removing file /vz/template/centos/8/x86_64/pm/base1-898e42d315451c2d/repodata/primary.xml.gz
Removing file /vz/template/centos/8/x86_64/pm/base1-898e42d315451c2d/repodata/repomd.xml
11 files removed
Cleaning up.
Temporary yum config /vz/tmp//vzpkg.cTJFUj/yum_conf.0mU3bm was created
Run /usr/share/vzyum/bin/yum from chroot(/vz/pkgenv/rpm414x64) with parameters:
/usr/share/vzyum/bin/yum
-y
-c
/vz/tmp//vzpkg.cTJFUj/yum_conf.0mU3bm
--basearch
x86_64
--installroot
/vz/tmp/vzpkg.cTJFUj
makecache
--allowerasing
And environments:
LD_PRELOAD=/usr/libexec/vztt_checker_open.so
VZTT_VEROOT=/vz/tmp/vzpkg.cTJFUj
PYTHONPATH=/vz/pkgenv/rpm414x64/usr/lib64//python3.6
SYSTEMD_LOG_TARGET=console
DNF_RELEASEVER=8
DNF_PLATFORM_ID=platform:el8
VZCTL_ENV=RPM_INSTALL_PREFIX:SYSTEMD_LOG_TARGET:DNF_RELEASEVER:DNF_PLATFORM_ID
timer: config: 1 ms
DNF version: 4.0.9
Command: dnf -y -c /vz/tmp//vzpkg.cTJFUj/yum_conf.0mU3bm --basearch x86_64 --installroot /vz/tmp/vzpkg.cTJFUj makecache --allowerasing
Installroot: /vz/tmp/vzpkg.cTJFUj
Releasever: 8
cachedir: /vz/template/centos/8/x86_64/pm/
Base command: makecache
Extra commands: ['-y', '-c', '/vz/tmp//vzpkg.cTJFUj/yum_conf.0mU3bm', '--basearch', 'x86_64', '--installroot', '/vz/tmp/vzpkg.cTJFUj', 'makecache', '--allowerasing']
Making cache files for all metadata files.
base0: has expired and will be refreshed.
base1: has expired and will be refreshed.
base2: has expired and will be refreshed.
base3: has expired and will be refreshed.
base4: has expired and will be refreshed.
base5: has expired and will be refreshed.
repo: downloading from remote: base0
base0                                           704  B/s | 1.6 kB     00:02
not found other for:
not found modules for:
not found deltainfo for:
not found updateinfo for:
base0: using metadata from Wed Sep 13 20:22:23 2023.
repo: downloading from remote: base1
base1                                           310  B/s | 1.0 kB     00:03
not found other for:
not found modules for:
not found deltainfo for:
not found updateinfo for:
base1: using metadata from Tue Nov 19 15:46:40 2019.
repo: downloading from remote: base2
base2                                            35  B/s |  38  B     00:01
Cannot download 'http://mirrorlist.centos.org/?release=8&arch=x86_64&repo=BaseOS': Cannot prepare internal mirrorlist: No URLs in mirrorlist.
Cleaning up.
Error: Failed to synchronize cache for repo 'base2'
Error: /usr/share/vzyum/bin/yum failed, exitcode=1
lock file unlocked
template unlocked
Failed to upgrade container from 7 to 8 family
```

Ignacio

**Comment by toddr** [comment]
This appears to be from logic in the almaconvert8 script. Please reach out to them for further assistance.

**Comment by AVasiljev** [comment]
Hello, @imorandinwnp can you clarify which vzdeploy8 version is used? Can you check whether OpenVZ installation is not isolated from the Internet?

**Comment by imorandinwnp** [comment]
Hi @AVasiljev . I'm using this version: [vzdeploy8-1.0.66-4.vl7.noarch.rpm](https://repo.virtuozzo.com/vzlinux/vzdeploy/vzdeploy8-1.0.66-4.vl7.noarch.rpm)
It is not isolated from the internet.

Thanks,
Ignacio

**Comment by AVasiljev** [comment]
@imorandinwnp What is the initial Template in container? It seems  like it became in CentOS8 state which shouldn't be the case. Either there is some bug with detection or container itself initially was inconsistent.

**Comment by imorandinwnp** [comment]
@AVasiljev : Yes I think the problem has to do with the templates as I see some strange behaviour in the yum output (it lists my templates for some reason). I'll try to do a new upgrade and send you the output. What ez packages do you recommend to have? almalinux-8-x86_64-ez and vzlinux-8-x86_64-ez only? thanks

**Comment by AVasiljev** [comment]
@imorandinwnp In fact you ought to have almalinux-8-x86_64-ez and vzlinux-8-x86_64-ez since the RHEL7 family is upgraded to vzlinux8 and then any RHEL8 family converted to Alma8.  However in your logs stated CentOS8 trying to upgrade itself. So I wondering how did you get to this state? Seems like you tried to upgrade this container manually before almaconvert8 execution.

**Comment by imorandinwnp** [comment]
@AVasiljev : I've tried deleting all templates except for AL8 and vzlinux 8 but it complains about CentOS 8 template:

```
[root@svm-spare template]# almaconvert8 convert -v --elevate --log /root/almaconvert.log $CTID
Error: Nothing to do
Error: Nothing to do
Error: Failed to install the template(s):
Error: centos-8-x86_64-ez
Error: centos-8-x86_64-x86_64-ez
Traceback (most recent call last):
  File "/bin/almaconvert8", line 827, in <module>
    args.func()
  File "/bin/almaconvert8", line 289, in process_cts
    results = pool.map(process_single_ct, args.CT)
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/bin/almaconvert8", line 400, in process_single_ct
    old_pkg_list_raw = subprocess.check_output(['/sbin/vzpkg', 'list', '-p', ct]).decode('utf-8')
  File "/usr/lib64/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib64/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/sbin/vzpkg', 'list', '-p', '1258']' returned non-zero exit status 24.
```

But centos-8 ez template isn't available anymore:

```
[root@svm-spare template]# yum search centos
Loaded plugins: fastestmirror, langpacks, openvz, priorities, vzlinux
Loading mirror speeds from cached hostfile
 * epel: d2lzkl7pfhq30w.cloudfront.net
 * openvz-os: mirror.trouble-free.net
 * openvz-updates: mirror.trouble-free.net
 * soluslabs: repo-usa-dallas.solusvm.com
 * solusvm-2-software-base: repo-france-1.solusvm.com
 * solusvm-2-stack-base: repo-france-1.solusvm.com
950 packages excluded due to repository priority protections
=================================================================== N/S matched: centos ====================================================================
centos-6-x86_64-ez.noarch : Centos 6 (for AMD64/Intel EM64T) Template set
centos-7-x86_64-ez.noarch : Centos 7 (for AMD64/Intel EM64T) Template set
centos-release-scl.noarch : Software collections from the CentOS SCLo SIG
centos-release-scl-rh.noarch : Software collections from the CentOS SCLo SIG (upstream scl only)
libreport-centos.x86_64 : libreport's CentOS Bug Tracker workflow
mock-centos-sig-configs.noarch : Mock configs for CentOS SIGs
rpminspect-data-centos.noarch : Build deviation compliance tool data files for CentOS
centpkg.noarch : CentOS utility for working with dist-git
centpkg-sig.noarch : CentOS SIG utility for working with dist-git
kabi-yum-plugins.noarch : The CentOS Linux kernel ABI yum plugin
kernel-abi-whitelists.noarch : The CentOS Linux kernel ABI symbol whitelists
rhel-7-x86_64-ez.noarch : Centos 7 (for AMD64/Intel EM64T) Template set
rhel-8-x86_64-ez.noarch : Centos 8 (for AMD64/Intel EM64T) Template set
rhel-9-x86_64-ez.noarch : Centos 9 (for AMD64/Intel EM64T) Template set
vzdeploy8.noarch : Upgrades CentOS or RHEL 8 distros to Virtuozzo Linux 8 or convert to Almalinux8
```

All package are the latest (kernel, vzdeploy, almaconvert8, etc).

**Comment by imorandinwnp** [comment]
As a workaround I did this:

1. Clean /vz/template folder
2. reinstall all necessary packages:
`yum reinstall almalinux-8-x86_64-ez vzlinux-8-x86_64-ez vzlinux-7-x86_64-ez centos-7-x86_64-ez -y`
3. I've "cheated" the script by copying the vzlinux template into centos 8 template:
`cp -ra /vz/template/vzlinux /vz/template/centos`
4. Ran the upgrade:
`almaconvert8 convert -v --elevate --log /root/almaconvert.log $CTID`
5. It starts and fails on stage 3 (I attach full output):

```
...

Installed:
 ct-preset-common       noarch    1:12-01.01
 ct-preset-systemd      noarch    1:12-01.01
 vz-dummy-systemd       noarch    1:12-01.01
/sbin/vzpkg: Cannot find upgrade for centos-8-x86_64 OS template
Failed to upgrade container from 7 to 8 family
```
[almaconvert8.log](https://github.com/cpanel/elevate/files/15044210/almaconvert8.log)

**Comment by imorandinwnp** [comment]
Keep in mind that the error reported at the beginning was with the centos-8 ez template installed (when it was available).

**Comment by AVasiljev** [comment]
@imorandinwnp Once again what container you tried to upgrade. Can you attach the ve.conf of container **pre upgrade?** it seems like the centos-8 container is treated like centos-7.

**Comment by AVasiljev** [comment]
Can you run almaconvert8 version also.

**Comment by imorandinwnp** [comment]
Hi. Sorry for the delay:

```
# almaconvert8 version
Almaconvert version: 1.0.66-4.vl7
```

So I've resumed the testing. Progress has been made, the last message I receive now is:

```
The following processes became active compared to the old container state:['agetty', 'elevate-']
1258: Warning!
The following processes became inactive compared to the old container state:['(agetty)', 'Passenge', 'abrt-wat', 'abrtd', 'anvil', 'auth', 'config', 'cpanel_p', 'cpanello', 'cpdavd -', 'cpsrvd (', 'crond', 'dnsadmin', 'dovecot', 'exim', 'gssproxy', 'httpd', 'imap-log', 'imunify-', 'iptables', 'leechpro', 'lfd - (c', 'lfd - ch', 'lfd - re', 'lfd HTTP', 'log', 'lvmetad', 'mariadbd', 'md5sum', 'nginx', 'php', 'php-fpm', 'pop3-log', 'python3', 'queuepro', 'run-scri', 'snmpd', 'spamd', 'spamd-st', 'sssd', 'sssd_aut', 'sssd_be', 'sssd_nss', 'sssd_pam', 'sssd_ssh', 'sssd_sud', 'stats', 'sw-engin', 'tailwatc', 'wrapper']
1258: Warning!
The following ports were open compared to the old container state:[('lfd\\x20HT', 'IPv6', 'TCP', '*:28888'), ('lfd\\x20TE', 'IPv6', 'TCP', '*:28889'), ('named', 'IPv6', 'TCP', '*:53'), ('named', 'IPv6', 'UDP', '*:53'), ('systemd', 'IPv4', 'TCP', '*:111'), ('systemd', 'IPv4', 'UDP', '*:111'), ('systemd', 'IPv6', 'TCP', '*:111'), ('systemd', 'IPv6', 'UDP', '*:111')]
1258: Warning!
The following ports were closed compared to the old container state:[('Passenger', 'IPv4', 'TCP', 'vps.pruebaupdateal8.com:43934->static.28.23.203.116.clients.your-server.de:443'), ('cpdavd', 'IPv4', 'TCP', '*:2077'), ('cpdavd', 'IPv4', 'TCP', '*:2078'), ('cpdavd', 'IPv4', 'TCP', '*:2091'), ('cpsrvd', 'IPv4', 'TCP', '*:2082'), ('cpsrvd', 'IPv4', 'TCP', '*:2083'), ('cpsrvd', 'IPv4', 'TCP', '*:2086'), ('cpsrvd', 'IPv4', 'TCP', '*:2087'), ('cpsrvd', 'IPv4', 'TCP', '*:2095'), ('cpsrvd', 'IPv4', 'TCP', '*:2096'), ('dovecot', 'IPv4', 'TCP', '*:110'), ('dovecot', 'IPv4', 'TCP', '*:143'), ('dovecot', 'IPv4', 'TCP', '*:993'), ('dovecot', 'IPv4', 'TCP', '*:995'), ('dovecot', 'IPv6', 'TCP', '*:110'), ('dovecot', 'IPv6', 'TCP', '*:143'), ('dovecot', 'IPv6', 'TCP', '*:993'), ('dovecot', 'IPv6', 'TCP', '*:995'), ('exim', 'IPv4', 'TCP', '*:25'), ('exim', 'IPv4', 'TCP', '*:465'), ('exim', 'IPv4', 'TCP', '*:587'), ('exim', 'IPv6', 'TCP', '*:25'), ('exim', 'IPv6', 'TCP', '*:465'), ('exim', 'IPv6', 'TCP', '*:587'), ('httpd', 'IPv4', 'TCP', '*:444'), ('httpd', 'IPv4', 'TCP', '*:81'), ('httpd', 'IPv6', 'TCP', '*:444'), ('httpd', 'IPv6', 'TCP', '*:81'), ('imap-logi', 'IPv4', 'TCP', '*:143'), ('imap-logi', 'IPv4', 'TCP', '*:993'), ('imap-logi', 'IPv6', 'TCP', '*:143'), ('imap-logi', 'IPv6', 'TCP', '*:993'), ('lfd', 'IPv4', 'TCP', 'localhost:40024->localhost:81'), ('lfd', 'IPv6', 'TCP', '*:28887'), ('lfd', 'IPv6', 'TCP', '*:28888'), ('lfd', 'IPv6', 'TCP', '*:28889'), ('mariadbd', 'IPv4', 'TCP', '*:3306'), ('mariadbd', 'IPv6', 'TCP', '*:3306'), ('named', 'IPv6', 'UDP', 'localhost:33298->c.root-servers.net:53'), ('named', 'IPv6', 'UDP', 'localhost:34685->G.ROOT-SERVERS.NET:53'), ('named', 'IPv6', 'UDP', 'localhost:36230->c.root-servers.net:53'), ('named', 'IPv6', 'UDP', 'localhost:38235->G.ROOT-SERVERS.NET:53'), ('named', 'IPv6', 'UDP', 'localhost:40578->G.ROOT-SERVERS.NET:53'), ('named', 'IPv6', 'UDP', 'localhost:41449->c.root-servers.net:53'), ('named', 'IPv6', 'UDP', 'localhost:42677->c.root-servers.net:53'), ('named', 'IPv6', 'UDP', 'localhost:43512->G.ROOT-SERVERS.NET:53'), ('named', 'IPv6', 'UDP', 'localhost:45907->G.ROOT-SERVERS.NET:53'), ('named', 'IPv6', 'UDP', 'localhost:48922->G.ROOT-SERVERS.NET:53'), ('named', 'IPv6', 'UDP', 'localhost:49956->c.root-servers.net:53'), ('named', 'IPv6', 'UDP', 'localhost:56398->G.ROOT-SERVERS.NET:53'), ('named', 'IPv6', 'UDP', 'localhost:58620->c.root-servers.net:53'), ('named', 'IPv6', 'UDP', 'localhost:59185->c.root-servers.net:53'), ('nginx', 'IPv4', 'TCP', '*:443'), ('nginx', 'IPv4', 'TCP', '*:80'), ('nginx', 'IPv6', 'TCP', '*:443'), ('nginx', 'IPv6', 'TCP', '*:80'), ('pop3-logi', 'IPv4', 'TCP', '*:110'), ('pop3-logi', 'IPv4', 'TCP', '*:995'), ('pop3-logi', 'IPv6', 'TCP', '*:110'), ('pop3-logi', 'IPv6', 'TCP', '*:995'), ('snmpd', 'IPv4', 'TCP', '*:1616'), ('snmpd', 'IPv4', 'TCP', 'localhost:199'), ('snmpd', 'IPv4', 'UDP', '*:1616'), ('spamd', 'IPv4', 'TCP', 'localhost:783'), ('sssd_be', 'IPv4', 'TCP', 'vps.pruebaupdateal8.com:35912->utils2.wnpower.com:636')]
1258: Conversion successful at 15:43:44.885747. Elevate will continue.
```

But it hangs and doesn't continue.
VM stuck with /waiting_for_distro_upgrade and VZlinux7:

```
CT-1258 /# cat /etc/redhat-release
Virtuozzo Linux release 8.5.0 (Vz)
```

These are all the commands I've executed so far:

```
## REMOVE ALL CUSTOM TEMPLATES SO THEY DON'T INTERFERE WITH THE PROCESS
mkdir /backup/template
mv /vz/template/* /backup/template

## REINSTALL ALL NEEDED TEMPLATES BACK
yum reinstall vzlinux-8-x86_64-ez centos-7-x86_64-ez almalinux-8-x86_64-ez -y

## VZDEPLOY WANTS TO UPDATE TO CENTOS8 BUT IT DOESN'T EXIST ANYMORE (AND ALSO THE REPOS ARE DOWN) SO WE COPY VZLINUX 8 TEMPLATE TO CENTOS 8
cp -ra /vz/template/vzlinux/8 /vz/template/centos/

## PRE-UPGRADE
prlctl snapshot $CTID
vzctl exec $CTID yum update -y
vzctl exec $CTID /scripts/upcp --force
vzctl exec $CTID yum remove btrfs-progs python3 ea-php5* ea-php70* ea-php71* python3-sssdconfig python*-sssdconfig python-sss sssd -y
vzctl exec $CTID rm -f /etc/cpupdate.conf
sed -i 's/^OSTEMPLATE=.*/OSTEMPLATE=\".centos-7-x86_64\"/' /etc/vz/conf/$CTID.conf
sed -i 's/^DISTRIBUTION=.*/DISTRIBUTION=\"centos\"/' /etc/vz/conf/$CTID.conf

## UGRADE
almaconvert8 convert -v --elevate $CTID 2>&1 | tee /root/almaconvert.log
```

I attach full log: [almaconvert.log](https://github.com/cpanel/elevate/files/15380934/almaconvert.log)

Thanks,

Ignacio

**Comment by AVasiljev** [comment]
Hello, Ignacio, seems like you are a way overdifficulting your process.

**Comment by imorandinwnp** [comment]
I've removed the kernel packages and now those errors don't appear but it does the same, it gets stuck on:

`1258: Conversion successful at 09:57:49.922924. Elevate will continue.`

**Comment by AVasiljev** [comment]
That is really odd. Why would you need kernel in CT?

**Comment by imorandinwnp** [comment]
I can give you access to the server if you want, let me know how to reach you. Thanks.

**Comment by AVasiljev** [comment]
For sure. reach me at artem.vasiliev@virtuozzo.com. Will create a task within Virtuozzo Jira and work that out. Seems like I have feeling I know where the bug is.
